---
title: "MLP Sources"
author: "Bedansh Pandey"
output: html_document
---



```{r setup}
install.packages("readxl")
library(tidyr)
library(readxl)
library(dplyr)
install.packages("here")



```
```{r}
#binding the four new LN sheets together 
file.exists("/Users/bedanshpandey/Downloads/Nexis_sources_Cental-SE_Asia 4")
list.files("/Users/bedanshpandey/Downloads")
list.files("/Users/bedanshpandey/Downloads/Nexis_sources_Cental-SE_Asia 4")


file_1 <- "/Users/bedanshpandey/Downloads/Nexis_sources_Cental-SE_Asia 4/Nexis_East_Timor.xlsx"
file_2 <- "/Users/bedanshpandey/Downloads/Nexis_sources_Cental-SE_Asia 4/Nexis_Sources_Africa_Americas_Europe.xlsx"
file_3 <- "/Users/bedanshpandey/Downloads/Nexis_sources_Cental-SE_Asia 4/Nexis_Sources_.South-West_Asia.xlsx"
file_4 <- "/Users/bedanshpandey/Downloads/Nexis_sources_Cental-SE_Asia 4/Nexis_sources_Cental-SE_Asia.xlsx"

df_1 <- read_excel(file_1, sheet = "Results")
df_2 <- read_excel(file_2, sheet = "Results")
df_3 <- read_excel(file_3, sheet = "Results")
df_4 <- read_excel(file_4, sheet = "Results")

new_LN <- bind_rows(df_1, df_2, df_3, df_4)

View(new_LN)
write.csv(new_LN, "/Users/bedanshpandey/Downloads/combined_data_new_LN.csv", row.names = FALSE)

# Rename "Title" to "Publication Name" in new_LN
colnames(new_LN)[colnames(new_LN) == "Title"] <- "Publication Name"
View(new_LN)

#Reading in the old LN 
file_path <- "/Users/bedanshpandey/Downloads/source_comparison 6/Nexis Uni -- Content Listing--non-US (2023).csv"
old_LN <- read.csv(file_path)
View(old_LN)

#Renaming one column in old_LN to get a key betweeen old_LN and new _LN
colnames(old_LN)[colnames(old_LN) == "Publication.Name"] <- "Publication Name"
View(old_LN)

#merging old_LN and new_LN together 
combined_LN <- merge(old_LN, new_LN, by = "Publication Name")
View(combined_LN)
write.csv(combined_LN, "/Users/bedanshpandey/Downloads/combined_data_LN.csv", row.names = FALSE)





```

```{r}
