---
title: "shock_detection"
author: "Donald Moratz"
date: "2024-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(ggplot2)
library(tidyverse)
```

```{r, include=FALSE, echo = FALSE}
#Load Permanent versions of the data
wd = here::here()

path_dropbox <- function(...) {
  # default guess
  base <- "~/Dropbox/ML for Peace/"

  # user/computer-specific alternatives
  if (Sys.info()["user"]=="andybega") {
    base <- "~/Dropbox/Work/ML for Peace/"
  }
  # jeremy: office windows
  if (Sys.info()["user"]=="jerem") {
    base <- "C:/Users/jerem/Dropbox/ML for Peace/"
  }
  # jeremy: home linux
  if (Sys.info()["user"]=="jerem") {
    base <- "/home/jeremy/Dropbox/ML for Peace/"
  }
  # donald
  if(Sys.info()["user"] == "skybl") {
    if(Sys.info()["nodename"] == "DONALDS_DESKTOP"){
      base <- "C:/Users/skybl/Dropbox/ML for Peace/"
    } else{
     base <- "D:/Dropbox/ML for Peace/" 
    }
  }
  # Check to make sure the directory exists and is correct
  if (!dir.exists(base)) {
    stop("Go edit path_dropbox in the code chunk and add your path to the Dropbox folder")
  }

  file.path(base, ...)
}

dropbox <- path_dropbox()

github <- here() %>% str_remove("mlp-data-intro")
```


```{r}
plot_variable = function(country, event){
  
  # Define variable
  var = event
  var_shk = gsub("Norm" , "", event)
  
  # Setup label mapping dataframe
  choices_df = data.frame(
    id = c("f1", "arrestNorm", "censorNorm", "corruptionNorm", "activismNorm", "cooperateNorm", "defamationcaseNorm", "legalactionNorm", "legalchangeNorm", "protestNorm", "purgeNorm", "raidNorm", "threatenNorm", "violencelethalNorm", "violencenonlethalNorm", "mobilizesecurityNorm"),
    names = c("Civic Space Index", "Arrests", "Censorship", "Corruption", "Civic Activism", "Political Cooperation", "Defamation Cases", "Legal Actions","Legal Changes",  "Protests", "Purges", "Raids", "Political Threats","Lethal Violence", "Non-lethal Violence", "Mobilize Troops") 
  )
  
  # Read-in data
  # categories = dat
  #categories = read_csv(here("forecast/data", paste0(country, "-indicators.csv")))
  categories = readr::read_csv(here::here("data", "counts", paste0(country,".csv")))
  
  categories = categories[, c("date", var)]
  categories$date_my = parse_date_time(categories$date, "ymd")
  
  pred_data = categories
  pred_data$date_my = parse_date_time(pred_data$date, "ymd")
  
  ends = nrow(pred_data)
  starts = ends-35
  pred_data = pred_data[starts:ends,]
  # Date breaks
  des_break = pred_data$date_my[c(TRUE, FALSE)]
  
  pred_data = as.data.frame(pred_data)
  
  shk = read_csv(paste0(github,"ML4P-Shiny-Tools/csews/predictions/", paste0("predictions_lag_1_", country, ".csv")) )
  
  pred_data = left_join(pred_data, shk)
  
  title = choices_df[choices_df$id == var,]$names
  if(title %in% c("Civic Space Index")){
    graph_y_lab = paste(title)
    title = paste("Shocks in", country, title)
  } else{
    graph_y_lab = paste("% of Articles on", title)
    title = paste("Shocks in", country, title)
  }

  top_val = max(pred_data[[var]], na.rm = T)
  a = ggplot(pred_data, aes(x = date_my, y = get(var))) +
    geom_line(linewidth = 1, color = "black", linetype=1) +
    geom_point(data = subset(pred_data, get(var_shk) == 1), aes(x = date_my, y = get(var)), color = "red", size = 2.5) +
    theme_bw() +
    scale_x_datetime(breaks = des_break, date_labels = "%b %y", date_minor_breaks = "1 month",
                     expand = expansion(mult = c(-0.03, .02))) +
    labs(y = graph_y_lab, x = "Date") +
    ggtitle(title) +
    theme(plot.title = element_text(hjust = 0, size = 18),  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    if(!event == "f1"){ scale_y_continuous(labels = scales::percent_format() ) }

  return(a)
  
}
```

```{r}
indonesia_arrest_shocks <- plot_variable("Indonesia", "arrestNorm")

indonesia_arrest_shocks

ggsave(paste0(here(),"/shock detection/indonesia_arrest_shock_detection.jpg"), plot = indonesia_arrest_shocks, height = 5, width = 7)
```

